### ISSUE TITLE
Including other repository metadata?

### ISSUE THREAD

**Issue by karllhughes** [peter-evans/s3-backup#3]
I'm looking into repository backup solutions. While I like the idea of using a GH action, it appears that s3-backup only saves the git repository data and none of the GitHub-specific metadata (eg: issues, PRs, wiki, etc.). Is this correct?

Also, I'm assuming adding support for this would be non-trivial?

Thanks!

**Comment by peter-evans** [comment]
Hi @karllhughes 

Yes, that is correct. This action only supports backup of the git repository.

I imagine that adding support for GitHub-specific metadata would be non-trivial because it would involve querying the API for all entities periodically, or somehow tracking changes. If there is an existing tool that does this, it might be possible to turn it into a GitHub action.

**Comment by karllhughes** [comment]
@peter-evans makes sense.

This is the other library I've been investigating: https://github.com/josegonzalez/python-github-backup

They use the GH API so their backups include metadata, but it's not packaged as a GitHub action.

It also doesn't have a method for recovering the repo, so it's admittedly limited in its own way.

Anyway, I'll close the issue as it's probably out of scope for this project, just wanted to confirm my assumptions. Thanks!

**Comment by peter-evans** [comment]
This API might be worth looking into. It appears you can use it to download an archive which may include metadata.
https://docs.github.com/en/free-pro-team@latest/rest/reference/migrations
